time ./MusicMindTest A1 B1 C1 
time ./MusicMindTest A1 B1 D1 
time ./MusicMindTest A1 C1 D1 
time ./MusicMindTest B1 C1 D1 
time ./MusicMindTest A1 B1 E1 
time ./MusicMindTest A1 C1 E1 
time ./MusicMindTest B1 C1 E1 
time ./MusicMindTest A1 D1 E1 
time ./MusicMindTest B1 D1 E1 
time ./MusicMindTest C1 D1 E1 
time ./MusicMindTest A1 B1 F1 
time ./MusicMindTest A1 C1 F1 
time ./MusicMindTest B1 C1 F1 
time ./MusicMindTest A1 D1 F1 
time ./MusicMindTest B1 D1 F1 
time ./MusicMindTest C1 D1 F1 
time ./MusicMindTest A1 E1 F1 
time ./MusicMindTest B1 E1 F1 
time ./MusicMindTest C1 E1 F1 
time ./MusicMindTest D1 E1 F1 
time ./MusicMindTest A1 B1 G1 
time ./MusicMindTest A1 C1 G1 
time ./MusicMindTest B1 C1 G1 
time ./MusicMindTest A1 D1 G1 
time ./MusicMindTest B1 D1 G1 
time ./MusicMindTest C1 D1 G1 
time ./MusicMindTest A1 E1 G1 
time ./MusicMindTest B1 E1 G1 
time ./MusicMindTest C1 E1 G1 
time ./MusicMindTest D1 E1 G1 
time ./MusicMindTest A1 F1 G1 
time ./MusicMindTest B1 F1 G1 
time ./MusicMindTest C1 F1 G1 
time ./MusicMindTest D1 F1 G1 
time ./MusicMindTest E1 F1 G1 
time ./MusicMindTest A1 B1 A2 
time ./MusicMindTest A1 C1 A2 
time ./MusicMindTest B1 C1 A2 
time ./MusicMindTest A1 D1 A2 
time ./MusicMindTest B1 D1 A2 
time ./MusicMindTest C1 D1 A2 
time ./MusicMindTest A1 E1 A2 
time ./MusicMindTest B1 E1 A2 
time ./MusicMindTest C1 E1 A2 
time ./MusicMindTest D1 E1 A2 
time ./MusicMindTest A1 F1 A2 
time ./MusicMindTest B1 F1 A2 
time ./MusicMindTest C1 F1 A2 
time ./MusicMindTest D1 F1 A2 
time ./MusicMindTest E1 F1 A2 
time ./MusicMindTest A1 G1 A2 
time ./MusicMindTest B1 G1 A2 
time ./MusicMindTest C1 G1 A2 
time ./MusicMindTest D1 G1 A2 
time ./MusicMindTest E1 G1 A2 
time ./MusicMindTest F1 G1 A2 
time ./MusicMindTest A1 B1 B2 
time ./MusicMindTest A1 C1 B2 
time ./MusicMindTest B1 C1 B2 
time ./MusicMindTest A1 D1 B2 
time ./MusicMindTest B1 D1 B2 
time ./MusicMindTest C1 D1 B2 
time ./MusicMindTest A1 E1 B2 
time ./MusicMindTest B1 E1 B2 
time ./MusicMindTest C1 E1 B2 
time ./MusicMindTest D1 E1 B2 
time ./MusicMindTest A1 F1 B2 
time ./MusicMindTest B1 F1 B2 
time ./MusicMindTest C1 F1 B2 
time ./MusicMindTest D1 F1 B2 
time ./MusicMindTest E1 F1 B2 
time ./MusicMindTest A1 G1 B2 
time ./MusicMindTest B1 G1 B2 
time ./MusicMindTest C1 G1 B2 
time ./MusicMindTest D1 G1 B2 
time ./MusicMindTest E1 G1 B2 
time ./MusicMindTest F1 G1 B2 
time ./MusicMindTest A1 A2 B2 
time ./MusicMindTest B1 A2 B2 
time ./MusicMindTest C1 A2 B2 
time ./MusicMindTest D1 A2 B2 
time ./MusicMindTest E1 A2 B2 
time ./MusicMindTest F1 A2 B2 
time ./MusicMindTest G1 A2 B2 
time ./MusicMindTest A1 B1 C2 
time ./MusicMindTest A1 C1 C2 
time ./MusicMindTest B1 C1 C2 
time ./MusicMindTest A1 D1 C2 
time ./MusicMindTest B1 D1 C2 
time ./MusicMindTest C1 D1 C2 
time ./MusicMindTest A1 E1 C2 
time ./MusicMindTest B1 E1 C2 
time ./MusicMindTest C1 E1 C2 
time ./MusicMindTest D1 E1 C2 
time ./MusicMindTest A1 F1 C2 
time ./MusicMindTest B1 F1 C2 
time ./MusicMindTest C1 F1 C2 
time ./MusicMindTest D1 F1 C2 
time ./MusicMindTest E1 F1 C2 
time ./MusicMindTest A1 G1 C2 
time ./MusicMindTest B1 G1 C2 
time ./MusicMindTest C1 G1 C2 
time ./MusicMindTest D1 G1 C2 
time ./MusicMindTest E1 G1 C2 
time ./MusicMindTest F1 G1 C2 
time ./MusicMindTest A1 A2 C2 
time ./MusicMindTest B1 A2 C2 
time ./MusicMindTest C1 A2 C2 
time ./MusicMindTest D1 A2 C2 
time ./MusicMindTest E1 A2 C2 
time ./MusicMindTest F1 A2 C2 
time ./MusicMindTest G1 A2 C2 
time ./MusicMindTest A1 B2 C2 
time ./MusicMindTest B1 B2 C2 
time ./MusicMindTest C1 B2 C2 
time ./MusicMindTest D1 B2 C2 
time ./MusicMindTest E1 B2 C2 
time ./MusicMindTest F1 B2 C2 
time ./MusicMindTest G1 B2 C2 
time ./MusicMindTest A2 B2 C2 
time ./MusicMindTest A1 B1 D2 
time ./MusicMindTest A1 C1 D2 
time ./MusicMindTest B1 C1 D2 
time ./MusicMindTest A1 D1 D2 
time ./MusicMindTest B1 D1 D2 
time ./MusicMindTest C1 D1 D2 
time ./MusicMindTest A1 E1 D2 
time ./MusicMindTest B1 E1 D2 
time ./MusicMindTest C1 E1 D2 
time ./MusicMindTest D1 E1 D2 
time ./MusicMindTest A1 F1 D2 
time ./MusicMindTest B1 F1 D2 
time ./MusicMindTest C1 F1 D2 
time ./MusicMindTest D1 F1 D2 
time ./MusicMindTest E1 F1 D2 
time ./MusicMindTest A1 G1 D2 
time ./MusicMindTest B1 G1 D2 
time ./MusicMindTest C1 G1 D2 
time ./MusicMindTest D1 G1 D2 
time ./MusicMindTest E1 G1 D2 
time ./MusicMindTest F1 G1 D2 
time ./MusicMindTest A1 A2 D2 
time ./MusicMindTest B1 A2 D2 
time ./MusicMindTest C1 A2 D2 
time ./MusicMindTest D1 A2 D2 
time ./MusicMindTest E1 A2 D2 
time ./MusicMindTest F1 A2 D2 
time ./MusicMindTest G1 A2 D2 
time ./MusicMindTest A1 B2 D2 
time ./MusicMindTest B1 B2 D2 
time ./MusicMindTest C1 B2 D2 
time ./MusicMindTest D1 B2 D2 
time ./MusicMindTest E1 B2 D2 
time ./MusicMindTest F1 B2 D2 
time ./MusicMindTest G1 B2 D2 
time ./MusicMindTest A2 B2 D2 
time ./MusicMindTest A1 C2 D2 
time ./MusicMindTest B1 C2 D2 
time ./MusicMindTest C1 C2 D2 
time ./MusicMindTest D1 C2 D2 
time ./MusicMindTest E1 C2 D2 
time ./MusicMindTest F1 C2 D2 
time ./MusicMindTest G1 C2 D2 
time ./MusicMindTest A2 C2 D2 
time ./MusicMindTest B2 C2 D2 
time ./MusicMindTest A1 B1 E2 
time ./MusicMindTest A1 C1 E2 
time ./MusicMindTest B1 C1 E2 
time ./MusicMindTest A1 D1 E2 
time ./MusicMindTest B1 D1 E2 
time ./MusicMindTest C1 D1 E2 
time ./MusicMindTest A1 E1 E2 
time ./MusicMindTest B1 E1 E2 
time ./MusicMindTest C1 E1 E2 
time ./MusicMindTest D1 E1 E2 
time ./MusicMindTest A1 F1 E2 
time ./MusicMindTest B1 F1 E2 
time ./MusicMindTest C1 F1 E2 
time ./MusicMindTest D1 F1 E2 
time ./MusicMindTest E1 F1 E2 
time ./MusicMindTest A1 G1 E2 
time ./MusicMindTest B1 G1 E2 
time ./MusicMindTest C1 G1 E2 
time ./MusicMindTest D1 G1 E2 
time ./MusicMindTest E1 G1 E2 
time ./MusicMindTest F1 G1 E2 
time ./MusicMindTest A1 A2 E2 
time ./MusicMindTest B1 A2 E2 
time ./MusicMindTest C1 A2 E2 
time ./MusicMindTest D1 A2 E2 
time ./MusicMindTest E1 A2 E2 
time ./MusicMindTest F1 A2 E2 
time ./MusicMindTest G1 A2 E2 
time ./MusicMindTest A1 B2 E2 
time ./MusicMindTest B1 B2 E2 
time ./MusicMindTest C1 B2 E2 
time ./MusicMindTest D1 B2 E2 
time ./MusicMindTest E1 B2 E2 
time ./MusicMindTest F1 B2 E2 
time ./MusicMindTest G1 B2 E2 
time ./MusicMindTest A2 B2 E2 
time ./MusicMindTest A1 C2 E2 
time ./MusicMindTest B1 C2 E2 
time ./MusicMindTest C1 C2 E2 
time ./MusicMindTest D1 C2 E2 
time ./MusicMindTest E1 C2 E2 
time ./MusicMindTest F1 C2 E2 
time ./MusicMindTest G1 C2 E2 
time ./MusicMindTest A2 C2 E2 
time ./MusicMindTest B2 C2 E2 
time ./MusicMindTest A1 D2 E2 
time ./MusicMindTest B1 D2 E2 
time ./MusicMindTest C1 D2 E2 
time ./MusicMindTest D1 D2 E2 
time ./MusicMindTest E1 D2 E2 
time ./MusicMindTest F1 D2 E2 
time ./MusicMindTest G1 D2 E2 
time ./MusicMindTest A2 D2 E2 
time ./MusicMindTest B2 D2 E2 
time ./MusicMindTest C2 D2 E2 
time ./MusicMindTest A1 B1 F2 
time ./MusicMindTest A1 C1 F2 
time ./MusicMindTest B1 C1 F2 
time ./MusicMindTest A1 D1 F2 
time ./MusicMindTest B1 D1 F2 
time ./MusicMindTest C1 D1 F2 
time ./MusicMindTest A1 E1 F2 
time ./MusicMindTest B1 E1 F2 
time ./MusicMindTest C1 E1 F2 
time ./MusicMindTest D1 E1 F2 
time ./MusicMindTest A1 F1 F2 
time ./MusicMindTest B1 F1 F2 
time ./MusicMindTest C1 F1 F2 
time ./MusicMindTest D1 F1 F2 
time ./MusicMindTest E1 F1 F2 
time ./MusicMindTest A1 G1 F2 
time ./MusicMindTest B1 G1 F2 
time ./MusicMindTest C1 G1 F2 
time ./MusicMindTest D1 G1 F2 
time ./MusicMindTest E1 G1 F2 
time ./MusicMindTest F1 G1 F2 
time ./MusicMindTest A1 A2 F2 
time ./MusicMindTest B1 A2 F2 
time ./MusicMindTest C1 A2 F2 
time ./MusicMindTest D1 A2 F2 
time ./MusicMindTest E1 A2 F2 
time ./MusicMindTest F1 A2 F2 
time ./MusicMindTest G1 A2 F2 
time ./MusicMindTest A1 B2 F2 
time ./MusicMindTest B1 B2 F2 
time ./MusicMindTest C1 B2 F2 
time ./MusicMindTest D1 B2 F2 
time ./MusicMindTest E1 B2 F2 
time ./MusicMindTest F1 B2 F2 
time ./MusicMindTest G1 B2 F2 
time ./MusicMindTest A2 B2 F2 
time ./MusicMindTest A1 C2 F2 
time ./MusicMindTest B1 C2 F2 
time ./MusicMindTest C1 C2 F2 
time ./MusicMindTest D1 C2 F2 
time ./MusicMindTest E1 C2 F2 
time ./MusicMindTest F1 C2 F2 
time ./MusicMindTest G1 C2 F2 
time ./MusicMindTest A2 C2 F2 
time ./MusicMindTest B2 C2 F2 
time ./MusicMindTest A1 D2 F2 
time ./MusicMindTest B1 D2 F2 
time ./MusicMindTest C1 D2 F2 
time ./MusicMindTest D1 D2 F2 
time ./MusicMindTest E1 D2 F2 
time ./MusicMindTest F1 D2 F2 
time ./MusicMindTest G1 D2 F2 
time ./MusicMindTest A2 D2 F2 
time ./MusicMindTest B2 D2 F2 
time ./MusicMindTest C2 D2 F2 
time ./MusicMindTest A1 E2 F2 
time ./MusicMindTest B1 E2 F2 
time ./MusicMindTest C1 E2 F2 
time ./MusicMindTest D1 E2 F2 
time ./MusicMindTest E1 E2 F2 
time ./MusicMindTest F1 E2 F2 
time ./MusicMindTest G1 E2 F2 
time ./MusicMindTest A2 E2 F2 
time ./MusicMindTest B2 E2 F2 
time ./MusicMindTest C2 E2 F2 
time ./MusicMindTest D2 E2 F2 
time ./MusicMindTest A1 B1 G2 
time ./MusicMindTest A1 C1 G2 
time ./MusicMindTest B1 C1 G2 
time ./MusicMindTest A1 D1 G2 
time ./MusicMindTest B1 D1 G2 
time ./MusicMindTest C1 D1 G2 
time ./MusicMindTest A1 E1 G2 
time ./MusicMindTest B1 E1 G2 
time ./MusicMindTest C1 E1 G2 
time ./MusicMindTest D1 E1 G2 
time ./MusicMindTest A1 F1 G2 
time ./MusicMindTest B1 F1 G2 
time ./MusicMindTest C1 F1 G2 
time ./MusicMindTest D1 F1 G2 
time ./MusicMindTest E1 F1 G2 
time ./MusicMindTest A1 G1 G2 
time ./MusicMindTest B1 G1 G2 
time ./MusicMindTest C1 G1 G2 
time ./MusicMindTest D1 G1 G2 
time ./MusicMindTest E1 G1 G2 
time ./MusicMindTest F1 G1 G2 
time ./MusicMindTest A1 A2 G2 
time ./MusicMindTest B1 A2 G2 
time ./MusicMindTest C1 A2 G2 
time ./MusicMindTest D1 A2 G2 
time ./MusicMindTest E1 A2 G2 
time ./MusicMindTest F1 A2 G2 
time ./MusicMindTest G1 A2 G2 
time ./MusicMindTest A1 B2 G2 
time ./MusicMindTest B1 B2 G2 
time ./MusicMindTest C1 B2 G2 
time ./MusicMindTest D1 B2 G2 
time ./MusicMindTest E1 B2 G2 
time ./MusicMindTest F1 B2 G2 
time ./MusicMindTest G1 B2 G2 
time ./MusicMindTest A2 B2 G2 
time ./MusicMindTest A1 C2 G2 
time ./MusicMindTest B1 C2 G2 
time ./MusicMindTest C1 C2 G2 
time ./MusicMindTest D1 C2 G2 
time ./MusicMindTest E1 C2 G2 
time ./MusicMindTest F1 C2 G2 
time ./MusicMindTest G1 C2 G2 
time ./MusicMindTest A2 C2 G2 
time ./MusicMindTest B2 C2 G2 
time ./MusicMindTest A1 D2 G2 
time ./MusicMindTest B1 D2 G2 
time ./MusicMindTest C1 D2 G2 
time ./MusicMindTest D1 D2 G2 
time ./MusicMindTest E1 D2 G2 
time ./MusicMindTest F1 D2 G2 
time ./MusicMindTest G1 D2 G2 
time ./MusicMindTest A2 D2 G2 
time ./MusicMindTest B2 D2 G2 
time ./MusicMindTest C2 D2 G2 
time ./MusicMindTest A1 E2 G2 
time ./MusicMindTest B1 E2 G2 
time ./MusicMindTest C1 E2 G2 
time ./MusicMindTest D1 E2 G2 
time ./MusicMindTest E1 E2 G2 
time ./MusicMindTest F1 E2 G2 
time ./MusicMindTest G1 E2 G2 
time ./MusicMindTest A2 E2 G2 
time ./MusicMindTest B2 E2 G2 
time ./MusicMindTest C2 E2 G2 
time ./MusicMindTest D2 E2 G2 
time ./MusicMindTest A1 F2 G2 
time ./MusicMindTest B1 F2 G2 
time ./MusicMindTest C1 F2 G2 
time ./MusicMindTest D1 F2 G2 
time ./MusicMindTest E1 F2 G2 
time ./MusicMindTest F1 F2 G2 
time ./MusicMindTest G1 F2 G2 
time ./MusicMindTest A2 F2 G2 
time ./MusicMindTest B2 F2 G2 
time ./MusicMindTest C2 F2 G2 
time ./MusicMindTest D2 F2 G2 
time ./MusicMindTest E2 F2 G2 
time ./MusicMindTest A1 B1 A3 
time ./MusicMindTest A1 C1 A3 
time ./MusicMindTest B1 C1 A3 
time ./MusicMindTest A1 D1 A3 
time ./MusicMindTest B1 D1 A3 
time ./MusicMindTest C1 D1 A3 
time ./MusicMindTest A1 E1 A3 
time ./MusicMindTest B1 E1 A3 
time ./MusicMindTest C1 E1 A3 
time ./MusicMindTest D1 E1 A3 
time ./MusicMindTest A1 F1 A3 
time ./MusicMindTest B1 F1 A3 
time ./MusicMindTest C1 F1 A3 
time ./MusicMindTest D1 F1 A3 
time ./MusicMindTest E1 F1 A3 
time ./MusicMindTest A1 G1 A3 
time ./MusicMindTest B1 G1 A3 
time ./MusicMindTest C1 G1 A3 
time ./MusicMindTest D1 G1 A3 
time ./MusicMindTest E1 G1 A3 
time ./MusicMindTest F1 G1 A3 
time ./MusicMindTest A1 A2 A3 
time ./MusicMindTest B1 A2 A3 
time ./MusicMindTest C1 A2 A3 
time ./MusicMindTest D1 A2 A3 
time ./MusicMindTest E1 A2 A3 
time ./MusicMindTest F1 A2 A3 
time ./MusicMindTest G1 A2 A3 
time ./MusicMindTest A1 B2 A3 
time ./MusicMindTest B1 B2 A3 
time ./MusicMindTest C1 B2 A3 
time ./MusicMindTest D1 B2 A3 
time ./MusicMindTest E1 B2 A3 
time ./MusicMindTest F1 B2 A3 
time ./MusicMindTest G1 B2 A3 
time ./MusicMindTest A2 B2 A3 
time ./MusicMindTest A1 C2 A3 
time ./MusicMindTest B1 C2 A3 
time ./MusicMindTest C1 C2 A3 
time ./MusicMindTest D1 C2 A3 
time ./MusicMindTest E1 C2 A3 
time ./MusicMindTest F1 C2 A3 
time ./MusicMindTest G1 C2 A3 
time ./MusicMindTest A2 C2 A3 
time ./MusicMindTest B2 C2 A3 
time ./MusicMindTest A1 D2 A3 
time ./MusicMindTest B1 D2 A3 
time ./MusicMindTest C1 D2 A3 
time ./MusicMindTest D1 D2 A3 
time ./MusicMindTest E1 D2 A3 
time ./MusicMindTest F1 D2 A3 
time ./MusicMindTest G1 D2 A3 
time ./MusicMindTest A2 D2 A3 
time ./MusicMindTest B2 D2 A3 
time ./MusicMindTest C2 D2 A3 
time ./MusicMindTest A1 E2 A3 
time ./MusicMindTest B1 E2 A3 
time ./MusicMindTest C1 E2 A3 
time ./MusicMindTest D1 E2 A3 
time ./MusicMindTest E1 E2 A3 
time ./MusicMindTest F1 E2 A3 
time ./MusicMindTest G1 E2 A3 
time ./MusicMindTest A2 E2 A3 
time ./MusicMindTest B2 E2 A3 
time ./MusicMindTest C2 E2 A3 
time ./MusicMindTest D2 E2 A3 
time ./MusicMindTest A1 F2 A3 
time ./MusicMindTest B1 F2 A3 
time ./MusicMindTest C1 F2 A3 
time ./MusicMindTest D1 F2 A3 
time ./MusicMindTest E1 F2 A3 
time ./MusicMindTest F1 F2 A3 
time ./MusicMindTest G1 F2 A3 
time ./MusicMindTest A2 F2 A3 
time ./MusicMindTest B2 F2 A3 
time ./MusicMindTest C2 F2 A3 
time ./MusicMindTest D2 F2 A3 
time ./MusicMindTest E2 F2 A3 
time ./MusicMindTest A1 G2 A3 
time ./MusicMindTest B1 G2 A3 
time ./MusicMindTest C1 G2 A3 
time ./MusicMindTest D1 G2 A3 
time ./MusicMindTest E1 G2 A3 
time ./MusicMindTest F1 G2 A3 
time ./MusicMindTest G1 G2 A3 
time ./MusicMindTest A2 G2 A3 
time ./MusicMindTest B2 G2 A3 
time ./MusicMindTest C2 G2 A3 
time ./MusicMindTest D2 G2 A3 
time ./MusicMindTest E2 G2 A3 
time ./MusicMindTest F2 G2 A3 
time ./MusicMindTest A1 B1 B3 
time ./MusicMindTest A1 C1 B3 
time ./MusicMindTest B1 C1 B3 
time ./MusicMindTest A1 D1 B3 
time ./MusicMindTest B1 D1 B3 
time ./MusicMindTest C1 D1 B3 
time ./MusicMindTest A1 E1 B3 
time ./MusicMindTest B1 E1 B3 
time ./MusicMindTest C1 E1 B3 
time ./MusicMindTest D1 E1 B3 
time ./MusicMindTest A1 F1 B3 
time ./MusicMindTest B1 F1 B3 
time ./MusicMindTest C1 F1 B3 
time ./MusicMindTest D1 F1 B3 
time ./MusicMindTest E1 F1 B3 
time ./MusicMindTest A1 G1 B3 
time ./MusicMindTest B1 G1 B3 
time ./MusicMindTest C1 G1 B3 
time ./MusicMindTest D1 G1 B3 
time ./MusicMindTest E1 G1 B3 
time ./MusicMindTest F1 G1 B3 
time ./MusicMindTest A1 A2 B3 
time ./MusicMindTest B1 A2 B3 
time ./MusicMindTest C1 A2 B3 
time ./MusicMindTest D1 A2 B3 
time ./MusicMindTest E1 A2 B3 
time ./MusicMindTest F1 A2 B3 
time ./MusicMindTest G1 A2 B3 
time ./MusicMindTest A1 B2 B3 
time ./MusicMindTest B1 B2 B3 
time ./MusicMindTest C1 B2 B3 
time ./MusicMindTest D1 B2 B3 
time ./MusicMindTest E1 B2 B3 
time ./MusicMindTest F1 B2 B3 
time ./MusicMindTest G1 B2 B3 
time ./MusicMindTest A2 B2 B3 
time ./MusicMindTest A1 C2 B3 
time ./MusicMindTest B1 C2 B3 
time ./MusicMindTest C1 C2 B3 
time ./MusicMindTest D1 C2 B3 
time ./MusicMindTest E1 C2 B3 
time ./MusicMindTest F1 C2 B3 
time ./MusicMindTest G1 C2 B3 
time ./MusicMindTest A2 C2 B3 
time ./MusicMindTest B2 C2 B3 
time ./MusicMindTest A1 D2 B3 
time ./MusicMindTest B1 D2 B3 
time ./MusicMindTest C1 D2 B3 
time ./MusicMindTest D1 D2 B3 
time ./MusicMindTest E1 D2 B3 
time ./MusicMindTest F1 D2 B3 
time ./MusicMindTest G1 D2 B3 
time ./MusicMindTest A2 D2 B3 
time ./MusicMindTest B2 D2 B3 
time ./MusicMindTest C2 D2 B3 
time ./MusicMindTest A1 E2 B3 
time ./MusicMindTest B1 E2 B3 
time ./MusicMindTest C1 E2 B3 
time ./MusicMindTest D1 E2 B3 
time ./MusicMindTest E1 E2 B3 
time ./MusicMindTest F1 E2 B3 
time ./MusicMindTest G1 E2 B3 
time ./MusicMindTest A2 E2 B3 
time ./MusicMindTest B2 E2 B3 
time ./MusicMindTest C2 E2 B3 
time ./MusicMindTest D2 E2 B3 
time ./MusicMindTest A1 F2 B3 
time ./MusicMindTest B1 F2 B3 
time ./MusicMindTest C1 F2 B3 
time ./MusicMindTest D1 F2 B3 
time ./MusicMindTest E1 F2 B3 
time ./MusicMindTest F1 F2 B3 
time ./MusicMindTest G1 F2 B3 
time ./MusicMindTest A2 F2 B3 
time ./MusicMindTest B2 F2 B3 
time ./MusicMindTest C2 F2 B3 
time ./MusicMindTest D2 F2 B3 
time ./MusicMindTest E2 F2 B3 
time ./MusicMindTest A1 G2 B3 
time ./MusicMindTest B1 G2 B3 
time ./MusicMindTest C1 G2 B3 
time ./MusicMindTest D1 G2 B3 
time ./MusicMindTest E1 G2 B3 
time ./MusicMindTest F1 G2 B3 
time ./MusicMindTest G1 G2 B3 
time ./MusicMindTest A2 G2 B3 
time ./MusicMindTest B2 G2 B3 
time ./MusicMindTest C2 G2 B3 
time ./MusicMindTest D2 G2 B3 
time ./MusicMindTest E2 G2 B3 
time ./MusicMindTest F2 G2 B3 
time ./MusicMindTest A1 A3 B3 
time ./MusicMindTest B1 A3 B3 
time ./MusicMindTest C1 A3 B3 
time ./MusicMindTest D1 A3 B3 
time ./MusicMindTest E1 A3 B3 
time ./MusicMindTest F1 A3 B3 
time ./MusicMindTest G1 A3 B3 
time ./MusicMindTest A2 A3 B3 
time ./MusicMindTest B2 A3 B3 
time ./MusicMindTest C2 A3 B3 
time ./MusicMindTest D2 A3 B3 
time ./MusicMindTest E2 A3 B3 
time ./MusicMindTest F2 A3 B3 
time ./MusicMindTest G2 A3 B3 
time ./MusicMindTest A1 B1 C3 
time ./MusicMindTest A1 C1 C3 
time ./MusicMindTest B1 C1 C3 
time ./MusicMindTest A1 D1 C3 
time ./MusicMindTest B1 D1 C3 
time ./MusicMindTest C1 D1 C3 
time ./MusicMindTest A1 E1 C3 
time ./MusicMindTest B1 E1 C3 
time ./MusicMindTest C1 E1 C3 
time ./MusicMindTest D1 E1 C3 
time ./MusicMindTest A1 F1 C3 
time ./MusicMindTest B1 F1 C3 
time ./MusicMindTest C1 F1 C3 
time ./MusicMindTest D1 F1 C3 
time ./MusicMindTest E1 F1 C3 
time ./MusicMindTest A1 G1 C3 
time ./MusicMindTest B1 G1 C3 
time ./MusicMindTest C1 G1 C3 
time ./MusicMindTest D1 G1 C3 
time ./MusicMindTest E1 G1 C3 
time ./MusicMindTest F1 G1 C3 
time ./MusicMindTest A1 A2 C3 
time ./MusicMindTest B1 A2 C3 
time ./MusicMindTest C1 A2 C3 
time ./MusicMindTest D1 A2 C3 
time ./MusicMindTest E1 A2 C3 
time ./MusicMindTest F1 A2 C3 
time ./MusicMindTest G1 A2 C3 
time ./MusicMindTest A1 B2 C3 
time ./MusicMindTest B1 B2 C3 
time ./MusicMindTest C1 B2 C3 
time ./MusicMindTest D1 B2 C3 
time ./MusicMindTest E1 B2 C3 
time ./MusicMindTest F1 B2 C3 
time ./MusicMindTest G1 B2 C3 
time ./MusicMindTest A2 B2 C3 
time ./MusicMindTest A1 C2 C3 
time ./MusicMindTest B1 C2 C3 
time ./MusicMindTest C1 C2 C3 
time ./MusicMindTest D1 C2 C3 
time ./MusicMindTest E1 C2 C3 
time ./MusicMindTest F1 C2 C3 
time ./MusicMindTest G1 C2 C3 
time ./MusicMindTest A2 C2 C3 
time ./MusicMindTest B2 C2 C3 
time ./MusicMindTest A1 D2 C3 
time ./MusicMindTest B1 D2 C3 
time ./MusicMindTest C1 D2 C3 
time ./MusicMindTest D1 D2 C3 
time ./MusicMindTest E1 D2 C3 
time ./MusicMindTest F1 D2 C3 
time ./MusicMindTest G1 D2 C3 
time ./MusicMindTest A2 D2 C3 
time ./MusicMindTest B2 D2 C3 
time ./MusicMindTest C2 D2 C3 
time ./MusicMindTest A1 E2 C3 
time ./MusicMindTest B1 E2 C3 
time ./MusicMindTest C1 E2 C3 
time ./MusicMindTest D1 E2 C3 
time ./MusicMindTest E1 E2 C3 
time ./MusicMindTest F1 E2 C3 
time ./MusicMindTest G1 E2 C3 
time ./MusicMindTest A2 E2 C3 
time ./MusicMindTest B2 E2 C3 
time ./MusicMindTest C2 E2 C3 
time ./MusicMindTest D2 E2 C3 
time ./MusicMindTest A1 F2 C3 
time ./MusicMindTest B1 F2 C3 
time ./MusicMindTest C1 F2 C3 
time ./MusicMindTest D1 F2 C3 
time ./MusicMindTest E1 F2 C3 
time ./MusicMindTest F1 F2 C3 
time ./MusicMindTest G1 F2 C3 
time ./MusicMindTest A2 F2 C3 
time ./MusicMindTest B2 F2 C3 
time ./MusicMindTest C2 F2 C3 
time ./MusicMindTest D2 F2 C3 
time ./MusicMindTest E2 F2 C3 
time ./MusicMindTest A1 G2 C3 
time ./MusicMindTest B1 G2 C3 
time ./MusicMindTest C1 G2 C3 
time ./MusicMindTest D1 G2 C3 
time ./MusicMindTest E1 G2 C3 
time ./MusicMindTest F1 G2 C3 
time ./MusicMindTest G1 G2 C3 
time ./MusicMindTest A2 G2 C3 
time ./MusicMindTest B2 G2 C3 
time ./MusicMindTest C2 G2 C3 
time ./MusicMindTest D2 G2 C3 
time ./MusicMindTest E2 G2 C3 
time ./MusicMindTest F2 G2 C3 
time ./MusicMindTest A1 A3 C3 
time ./MusicMindTest B1 A3 C3 
time ./MusicMindTest C1 A3 C3 
time ./MusicMindTest D1 A3 C3 
time ./MusicMindTest E1 A3 C3 
time ./MusicMindTest F1 A3 C3 
time ./MusicMindTest G1 A3 C3 
time ./MusicMindTest A2 A3 C3 
time ./MusicMindTest B2 A3 C3 
time ./MusicMindTest C2 A3 C3 
time ./MusicMindTest D2 A3 C3 
time ./MusicMindTest E2 A3 C3 
time ./MusicMindTest F2 A3 C3 
time ./MusicMindTest G2 A3 C3 
time ./MusicMindTest A1 B3 C3 
time ./MusicMindTest B1 B3 C3 
time ./MusicMindTest C1 B3 C3 
time ./MusicMindTest D1 B3 C3 
time ./MusicMindTest E1 B3 C3 
time ./MusicMindTest F1 B3 C3 
time ./MusicMindTest G1 B3 C3 
time ./MusicMindTest A2 B3 C3 
time ./MusicMindTest B2 B3 C3 
time ./MusicMindTest C2 B3 C3 
time ./MusicMindTest D2 B3 C3 
time ./MusicMindTest E2 B3 C3 
time ./MusicMindTest F2 B3 C3 
time ./MusicMindTest G2 B3 C3 
time ./MusicMindTest A3 B3 C3 
time ./MusicMindTest A1 B1 D3 
time ./MusicMindTest A1 C1 D3 
time ./MusicMindTest B1 C1 D3 
time ./MusicMindTest A1 D1 D3 
time ./MusicMindTest B1 D1 D3 
time ./MusicMindTest C1 D1 D3 
time ./MusicMindTest A1 E1 D3 
time ./MusicMindTest B1 E1 D3 
time ./MusicMindTest C1 E1 D3 
time ./MusicMindTest D1 E1 D3 
time ./MusicMindTest A1 F1 D3 
time ./MusicMindTest B1 F1 D3 
time ./MusicMindTest C1 F1 D3 
time ./MusicMindTest D1 F1 D3 
time ./MusicMindTest E1 F1 D3 
time ./MusicMindTest A1 G1 D3 
time ./MusicMindTest B1 G1 D3 
time ./MusicMindTest C1 G1 D3 
time ./MusicMindTest D1 G1 D3 
time ./MusicMindTest E1 G1 D3 
time ./MusicMindTest F1 G1 D3 
time ./MusicMindTest A1 A2 D3 
time ./MusicMindTest B1 A2 D3 
time ./MusicMindTest C1 A2 D3 
time ./MusicMindTest D1 A2 D3 
time ./MusicMindTest E1 A2 D3 
time ./MusicMindTest F1 A2 D3 
time ./MusicMindTest G1 A2 D3 
time ./MusicMindTest A1 B2 D3 
time ./MusicMindTest B1 B2 D3 
time ./MusicMindTest C1 B2 D3 
time ./MusicMindTest D1 B2 D3 
time ./MusicMindTest E1 B2 D3 
time ./MusicMindTest F1 B2 D3 
time ./MusicMindTest G1 B2 D3 
time ./MusicMindTest A2 B2 D3 
time ./MusicMindTest A1 C2 D3 
time ./MusicMindTest B1 C2 D3 
time ./MusicMindTest C1 C2 D3 
time ./MusicMindTest D1 C2 D3 
time ./MusicMindTest E1 C2 D3 
time ./MusicMindTest F1 C2 D3 
time ./MusicMindTest G1 C2 D3 
time ./MusicMindTest A2 C2 D3 
time ./MusicMindTest B2 C2 D3 
time ./MusicMindTest A1 D2 D3 
time ./MusicMindTest B1 D2 D3 
time ./MusicMindTest C1 D2 D3 
time ./MusicMindTest D1 D2 D3 
time ./MusicMindTest E1 D2 D3 
time ./MusicMindTest F1 D2 D3 
time ./MusicMindTest G1 D2 D3 
time ./MusicMindTest A2 D2 D3 
time ./MusicMindTest B2 D2 D3 
time ./MusicMindTest C2 D2 D3 
time ./MusicMindTest A1 E2 D3 
time ./MusicMindTest B1 E2 D3 
time ./MusicMindTest C1 E2 D3 
time ./MusicMindTest D1 E2 D3 
time ./MusicMindTest E1 E2 D3 
time ./MusicMindTest F1 E2 D3 
time ./MusicMindTest G1 E2 D3 
time ./MusicMindTest A2 E2 D3 
time ./MusicMindTest B2 E2 D3 
time ./MusicMindTest C2 E2 D3 
time ./MusicMindTest D2 E2 D3 
time ./MusicMindTest A1 F2 D3 
time ./MusicMindTest B1 F2 D3 
time ./MusicMindTest C1 F2 D3 
time ./MusicMindTest D1 F2 D3 
time ./MusicMindTest E1 F2 D3 
time ./MusicMindTest F1 F2 D3 
time ./MusicMindTest G1 F2 D3 
time ./MusicMindTest A2 F2 D3 
time ./MusicMindTest B2 F2 D3 
time ./MusicMindTest C2 F2 D3 
time ./MusicMindTest D2 F2 D3 
time ./MusicMindTest E2 F2 D3 
time ./MusicMindTest A1 G2 D3 
time ./MusicMindTest B1 G2 D3 
time ./MusicMindTest C1 G2 D3 
time ./MusicMindTest D1 G2 D3 
time ./MusicMindTest E1 G2 D3 
time ./MusicMindTest F1 G2 D3 
time ./MusicMindTest G1 G2 D3 
time ./MusicMindTest A2 G2 D3 
time ./MusicMindTest B2 G2 D3 
time ./MusicMindTest C2 G2 D3 
time ./MusicMindTest D2 G2 D3 
time ./MusicMindTest E2 G2 D3 
time ./MusicMindTest F2 G2 D3 
time ./MusicMindTest A1 A3 D3 
time ./MusicMindTest B1 A3 D3 
time ./MusicMindTest C1 A3 D3 
time ./MusicMindTest D1 A3 D3 
time ./MusicMindTest E1 A3 D3 
time ./MusicMindTest F1 A3 D3 
time ./MusicMindTest G1 A3 D3 
time ./MusicMindTest A2 A3 D3 
time ./MusicMindTest B2 A3 D3 
time ./MusicMindTest C2 A3 D3 
time ./MusicMindTest D2 A3 D3 
time ./MusicMindTest E2 A3 D3 
time ./MusicMindTest F2 A3 D3 
time ./MusicMindTest G2 A3 D3 
time ./MusicMindTest A1 B3 D3 
time ./MusicMindTest B1 B3 D3 
time ./MusicMindTest C1 B3 D3 
time ./MusicMindTest D1 B3 D3 
time ./MusicMindTest E1 B3 D3 
time ./MusicMindTest F1 B3 D3 
time ./MusicMindTest G1 B3 D3 
time ./MusicMindTest A2 B3 D3 
time ./MusicMindTest B2 B3 D3 
time ./MusicMindTest C2 B3 D3 
time ./MusicMindTest D2 B3 D3 
time ./MusicMindTest E2 B3 D3 
time ./MusicMindTest F2 B3 D3 
time ./MusicMindTest G2 B3 D3 
time ./MusicMindTest A3 B3 D3 
time ./MusicMindTest A1 C3 D3 
time ./MusicMindTest B1 C3 D3 
time ./MusicMindTest C1 C3 D3 
time ./MusicMindTest D1 C3 D3 
time ./MusicMindTest E1 C3 D3 
time ./MusicMindTest F1 C3 D3 
time ./MusicMindTest G1 C3 D3 
time ./MusicMindTest A2 C3 D3 
time ./MusicMindTest B2 C3 D3 
time ./MusicMindTest C2 C3 D3 
time ./MusicMindTest D2 C3 D3 
time ./MusicMindTest E2 C3 D3 
time ./MusicMindTest F2 C3 D3 
time ./MusicMindTest G2 C3 D3 
time ./MusicMindTest A3 C3 D3 
time ./MusicMindTest B3 C3 D3 
time ./MusicMindTest A1 B1 E3 
time ./MusicMindTest A1 C1 E3 
time ./MusicMindTest B1 C1 E3 
time ./MusicMindTest A1 D1 E3 
time ./MusicMindTest B1 D1 E3 
time ./MusicMindTest C1 D1 E3 
time ./MusicMindTest A1 E1 E3 
time ./MusicMindTest B1 E1 E3 
time ./MusicMindTest C1 E1 E3 
time ./MusicMindTest D1 E1 E3 
time ./MusicMindTest A1 F1 E3 
time ./MusicMindTest B1 F1 E3 
time ./MusicMindTest C1 F1 E3 
time ./MusicMindTest D1 F1 E3 
time ./MusicMindTest E1 F1 E3 
time ./MusicMindTest A1 G1 E3 
time ./MusicMindTest B1 G1 E3 
time ./MusicMindTest C1 G1 E3 
time ./MusicMindTest D1 G1 E3 
time ./MusicMindTest E1 G1 E3 
time ./MusicMindTest F1 G1 E3 
time ./MusicMindTest A1 A2 E3 
time ./MusicMindTest B1 A2 E3 
time ./MusicMindTest C1 A2 E3 
time ./MusicMindTest D1 A2 E3 
time ./MusicMindTest E1 A2 E3 
time ./MusicMindTest F1 A2 E3 
time ./MusicMindTest G1 A2 E3 
time ./MusicMindTest A1 B2 E3 
time ./MusicMindTest B1 B2 E3 
time ./MusicMindTest C1 B2 E3 
time ./MusicMindTest D1 B2 E3 
time ./MusicMindTest E1 B2 E3 
time ./MusicMindTest F1 B2 E3 
time ./MusicMindTest G1 B2 E3 
time ./MusicMindTest A2 B2 E3 
time ./MusicMindTest A1 C2 E3 
time ./MusicMindTest B1 C2 E3 
time ./MusicMindTest C1 C2 E3 
time ./MusicMindTest D1 C2 E3 
time ./MusicMindTest E1 C2 E3 
time ./MusicMindTest F1 C2 E3 
time ./MusicMindTest G1 C2 E3 
time ./MusicMindTest A2 C2 E3 
time ./MusicMindTest B2 C2 E3 
time ./MusicMindTest A1 D2 E3 
time ./MusicMindTest B1 D2 E3 
time ./MusicMindTest C1 D2 E3 
time ./MusicMindTest D1 D2 E3 
time ./MusicMindTest E1 D2 E3 
time ./MusicMindTest F1 D2 E3 
time ./MusicMindTest G1 D2 E3 
time ./MusicMindTest A2 D2 E3 
time ./MusicMindTest B2 D2 E3 
time ./MusicMindTest C2 D2 E3 
time ./MusicMindTest A1 E2 E3 
time ./MusicMindTest B1 E2 E3 
time ./MusicMindTest C1 E2 E3 
time ./MusicMindTest D1 E2 E3 
time ./MusicMindTest E1 E2 E3 
time ./MusicMindTest F1 E2 E3 
time ./MusicMindTest G1 E2 E3 
time ./MusicMindTest A2 E2 E3 
time ./MusicMindTest B2 E2 E3 
time ./MusicMindTest C2 E2 E3 
time ./MusicMindTest D2 E2 E3 
time ./MusicMindTest A1 F2 E3 
time ./MusicMindTest B1 F2 E3 
time ./MusicMindTest C1 F2 E3 
time ./MusicMindTest D1 F2 E3 
time ./MusicMindTest E1 F2 E3 
time ./MusicMindTest F1 F2 E3 
time ./MusicMindTest G1 F2 E3 
time ./MusicMindTest A2 F2 E3 
time ./MusicMindTest B2 F2 E3 
time ./MusicMindTest C2 F2 E3 
time ./MusicMindTest D2 F2 E3 
time ./MusicMindTest E2 F2 E3 
time ./MusicMindTest A1 G2 E3 
time ./MusicMindTest B1 G2 E3 
time ./MusicMindTest C1 G2 E3 
time ./MusicMindTest D1 G2 E3 
time ./MusicMindTest E1 G2 E3 
time ./MusicMindTest F1 G2 E3 
time ./MusicMindTest G1 G2 E3 
time ./MusicMindTest A2 G2 E3 
time ./MusicMindTest B2 G2 E3 
time ./MusicMindTest C2 G2 E3 
time ./MusicMindTest D2 G2 E3 
time ./MusicMindTest E2 G2 E3 
time ./MusicMindTest F2 G2 E3 
time ./MusicMindTest A1 A3 E3 
time ./MusicMindTest B1 A3 E3 
time ./MusicMindTest C1 A3 E3 
time ./MusicMindTest D1 A3 E3 
time ./MusicMindTest E1 A3 E3 
time ./MusicMindTest F1 A3 E3 
time ./MusicMindTest G1 A3 E3 
time ./MusicMindTest A2 A3 E3 
time ./MusicMindTest B2 A3 E3 
time ./MusicMindTest C2 A3 E3 
time ./MusicMindTest D2 A3 E3 
time ./MusicMindTest E2 A3 E3 
time ./MusicMindTest F2 A3 E3 
time ./MusicMindTest G2 A3 E3 
time ./MusicMindTest A1 B3 E3 
time ./MusicMindTest B1 B3 E3 
time ./MusicMindTest C1 B3 E3 
time ./MusicMindTest D1 B3 E3 
time ./MusicMindTest E1 B3 E3 
time ./MusicMindTest F1 B3 E3 
time ./MusicMindTest G1 B3 E3 
time ./MusicMindTest A2 B3 E3 
time ./MusicMindTest B2 B3 E3 
time ./MusicMindTest C2 B3 E3 
time ./MusicMindTest D2 B3 E3 
time ./MusicMindTest E2 B3 E3 
time ./MusicMindTest F2 B3 E3 
time ./MusicMindTest G2 B3 E3 
time ./MusicMindTest A3 B3 E3 
time ./MusicMindTest A1 C3 E3 
time ./MusicMindTest B1 C3 E3 
time ./MusicMindTest C1 C3 E3 
time ./MusicMindTest D1 C3 E3 
time ./MusicMindTest E1 C3 E3 
time ./MusicMindTest F1 C3 E3 
time ./MusicMindTest G1 C3 E3 
time ./MusicMindTest A2 C3 E3 
time ./MusicMindTest B2 C3 E3 
time ./MusicMindTest C2 C3 E3 
time ./MusicMindTest D2 C3 E3 
time ./MusicMindTest E2 C3 E3 
time ./MusicMindTest F2 C3 E3 
time ./MusicMindTest G2 C3 E3 
time ./MusicMindTest A3 C3 E3 
time ./MusicMindTest B3 C3 E3 
time ./MusicMindTest A1 D3 E3 
time ./MusicMindTest B1 D3 E3 
time ./MusicMindTest C1 D3 E3 
time ./MusicMindTest D1 D3 E3 
time ./MusicMindTest E1 D3 E3 
time ./MusicMindTest F1 D3 E3 
time ./MusicMindTest G1 D3 E3 
time ./MusicMindTest A2 D3 E3 
time ./MusicMindTest B2 D3 E3 
time ./MusicMindTest C2 D3 E3 
time ./MusicMindTest D2 D3 E3 
time ./MusicMindTest E2 D3 E3 
time ./MusicMindTest F2 D3 E3 
time ./MusicMindTest G2 D3 E3 
time ./MusicMindTest A3 D3 E3 
time ./MusicMindTest B3 D3 E3 
time ./MusicMindTest C3 D3 E3 
time ./MusicMindTest A1 B1 F3 
time ./MusicMindTest A1 C1 F3 
time ./MusicMindTest B1 C1 F3 
time ./MusicMindTest A1 D1 F3 
time ./MusicMindTest B1 D1 F3 
time ./MusicMindTest C1 D1 F3 
time ./MusicMindTest A1 E1 F3 
time ./MusicMindTest B1 E1 F3 
time ./MusicMindTest C1 E1 F3 
time ./MusicMindTest D1 E1 F3 
time ./MusicMindTest A1 F1 F3 
time ./MusicMindTest B1 F1 F3 
time ./MusicMindTest C1 F1 F3 
time ./MusicMindTest D1 F1 F3 
time ./MusicMindTest E1 F1 F3 
time ./MusicMindTest A1 G1 F3 
time ./MusicMindTest B1 G1 F3 
time ./MusicMindTest C1 G1 F3 
time ./MusicMindTest D1 G1 F3 
time ./MusicMindTest E1 G1 F3 
time ./MusicMindTest F1 G1 F3 
time ./MusicMindTest A1 A2 F3 
time ./MusicMindTest B1 A2 F3 
time ./MusicMindTest C1 A2 F3 
time ./MusicMindTest D1 A2 F3 
time ./MusicMindTest E1 A2 F3 
time ./MusicMindTest F1 A2 F3 
time ./MusicMindTest G1 A2 F3 
time ./MusicMindTest A1 B2 F3 
time ./MusicMindTest B1 B2 F3 
time ./MusicMindTest C1 B2 F3 
time ./MusicMindTest D1 B2 F3 
time ./MusicMindTest E1 B2 F3 
time ./MusicMindTest F1 B2 F3 
time ./MusicMindTest G1 B2 F3 
time ./MusicMindTest A2 B2 F3 
time ./MusicMindTest A1 C2 F3 
time ./MusicMindTest B1 C2 F3 
time ./MusicMindTest C1 C2 F3 
time ./MusicMindTest D1 C2 F3 
time ./MusicMindTest E1 C2 F3 
time ./MusicMindTest F1 C2 F3 
time ./MusicMindTest G1 C2 F3 
time ./MusicMindTest A2 C2 F3 
time ./MusicMindTest B2 C2 F3 
time ./MusicMindTest A1 D2 F3 
time ./MusicMindTest B1 D2 F3 
time ./MusicMindTest C1 D2 F3 
time ./MusicMindTest D1 D2 F3 
time ./MusicMindTest E1 D2 F3 
time ./MusicMindTest F1 D2 F3 
time ./MusicMindTest G1 D2 F3 
time ./MusicMindTest A2 D2 F3 
time ./MusicMindTest B2 D2 F3 
time ./MusicMindTest C2 D2 F3 
time ./MusicMindTest A1 E2 F3 
time ./MusicMindTest B1 E2 F3 
time ./MusicMindTest C1 E2 F3 
time ./MusicMindTest D1 E2 F3 
time ./MusicMindTest E1 E2 F3 
time ./MusicMindTest F1 E2 F3 
time ./MusicMindTest G1 E2 F3 
time ./MusicMindTest A2 E2 F3 
time ./MusicMindTest B2 E2 F3 
time ./MusicMindTest C2 E2 F3 
time ./MusicMindTest D2 E2 F3 
time ./MusicMindTest A1 F2 F3 
time ./MusicMindTest B1 F2 F3 
time ./MusicMindTest C1 F2 F3 
time ./MusicMindTest D1 F2 F3 
time ./MusicMindTest E1 F2 F3 
time ./MusicMindTest F1 F2 F3 
time ./MusicMindTest G1 F2 F3 
time ./MusicMindTest A2 F2 F3 
time ./MusicMindTest B2 F2 F3 
time ./MusicMindTest C2 F2 F3 
time ./MusicMindTest D2 F2 F3 
time ./MusicMindTest E2 F2 F3 
time ./MusicMindTest A1 G2 F3 
time ./MusicMindTest B1 G2 F3 
time ./MusicMindTest C1 G2 F3 
time ./MusicMindTest D1 G2 F3 
time ./MusicMindTest E1 G2 F3 
time ./MusicMindTest F1 G2 F3 
time ./MusicMindTest G1 G2 F3 
time ./MusicMindTest A2 G2 F3 
time ./MusicMindTest B2 G2 F3 
time ./MusicMindTest C2 G2 F3 
time ./MusicMindTest D2 G2 F3 
time ./MusicMindTest E2 G2 F3 
time ./MusicMindTest F2 G2 F3 
time ./MusicMindTest A1 A3 F3 
time ./MusicMindTest B1 A3 F3 
time ./MusicMindTest C1 A3 F3 
time ./MusicMindTest D1 A3 F3 
time ./MusicMindTest E1 A3 F3 
time ./MusicMindTest F1 A3 F3 
time ./MusicMindTest G1 A3 F3 
time ./MusicMindTest A2 A3 F3 
time ./MusicMindTest B2 A3 F3 
time ./MusicMindTest C2 A3 F3 
time ./MusicMindTest D2 A3 F3 
time ./MusicMindTest E2 A3 F3 
time ./MusicMindTest F2 A3 F3 
time ./MusicMindTest G2 A3 F3 
time ./MusicMindTest A1 B3 F3 
time ./MusicMindTest B1 B3 F3 
time ./MusicMindTest C1 B3 F3 
time ./MusicMindTest D1 B3 F3 
time ./MusicMindTest E1 B3 F3 
time ./MusicMindTest F1 B3 F3 
time ./MusicMindTest G1 B3 F3 
time ./MusicMindTest A2 B3 F3 
time ./MusicMindTest B2 B3 F3 
time ./MusicMindTest C2 B3 F3 
time ./MusicMindTest D2 B3 F3 
time ./MusicMindTest E2 B3 F3 
time ./MusicMindTest F2 B3 F3 
time ./MusicMindTest G2 B3 F3 
time ./MusicMindTest A3 B3 F3 
time ./MusicMindTest A1 C3 F3 
time ./MusicMindTest B1 C3 F3 
time ./MusicMindTest C1 C3 F3 
time ./MusicMindTest D1 C3 F3 
time ./MusicMindTest E1 C3 F3 
time ./MusicMindTest F1 C3 F3 
time ./MusicMindTest G1 C3 F3 
time ./MusicMindTest A2 C3 F3 
time ./MusicMindTest B2 C3 F3 
time ./MusicMindTest C2 C3 F3 
time ./MusicMindTest D2 C3 F3 
time ./MusicMindTest E2 C3 F3 
time ./MusicMindTest F2 C3 F3 
time ./MusicMindTest G2 C3 F3 
time ./MusicMindTest A3 C3 F3 
time ./MusicMindTest B3 C3 F3 
time ./MusicMindTest A1 D3 F3 
time ./MusicMindTest B1 D3 F3 
time ./MusicMindTest C1 D3 F3 
time ./MusicMindTest D1 D3 F3 
time ./MusicMindTest E1 D3 F3 
time ./MusicMindTest F1 D3 F3 
time ./MusicMindTest G1 D3 F3 
time ./MusicMindTest A2 D3 F3 
time ./MusicMindTest B2 D3 F3 
time ./MusicMindTest C2 D3 F3 
time ./MusicMindTest D2 D3 F3 
time ./MusicMindTest E2 D3 F3 
time ./MusicMindTest F2 D3 F3 
time ./MusicMindTest G2 D3 F3 
time ./MusicMindTest A3 D3 F3 
time ./MusicMindTest B3 D3 F3 
time ./MusicMindTest C3 D3 F3 
time ./MusicMindTest A1 E3 F3 
time ./MusicMindTest B1 E3 F3 
time ./MusicMindTest C1 E3 F3 
time ./MusicMindTest D1 E3 F3 
time ./MusicMindTest E1 E3 F3 
time ./MusicMindTest F1 E3 F3 
time ./MusicMindTest G1 E3 F3 
time ./MusicMindTest A2 E3 F3 
time ./MusicMindTest B2 E3 F3 
time ./MusicMindTest C2 E3 F3 
time ./MusicMindTest D2 E3 F3 
time ./MusicMindTest E2 E3 F3 
time ./MusicMindTest F2 E3 F3 
time ./MusicMindTest G2 E3 F3 
time ./MusicMindTest A3 E3 F3 
time ./MusicMindTest B3 E3 F3 
time ./MusicMindTest C3 E3 F3 
time ./MusicMindTest D3 E3 F3 
time ./MusicMindTest A1 B1 G3 
time ./MusicMindTest A1 C1 G3 
time ./MusicMindTest B1 C1 G3 
time ./MusicMindTest A1 D1 G3 
time ./MusicMindTest B1 D1 G3 
time ./MusicMindTest C1 D1 G3 
time ./MusicMindTest A1 E1 G3 
time ./MusicMindTest B1 E1 G3 
time ./MusicMindTest C1 E1 G3 
time ./MusicMindTest D1 E1 G3 
time ./MusicMindTest A1 F1 G3 
time ./MusicMindTest B1 F1 G3 
time ./MusicMindTest C1 F1 G3 
time ./MusicMindTest D1 F1 G3 
time ./MusicMindTest E1 F1 G3 
time ./MusicMindTest A1 G1 G3 
time ./MusicMindTest B1 G1 G3 
time ./MusicMindTest C1 G1 G3 
time ./MusicMindTest D1 G1 G3 
time ./MusicMindTest E1 G1 G3 
time ./MusicMindTest F1 G1 G3 
time ./MusicMindTest A1 A2 G3 
time ./MusicMindTest B1 A2 G3 
time ./MusicMindTest C1 A2 G3 
time ./MusicMindTest D1 A2 G3 
time ./MusicMindTest E1 A2 G3 
time ./MusicMindTest F1 A2 G3 
time ./MusicMindTest G1 A2 G3 
time ./MusicMindTest A1 B2 G3 
time ./MusicMindTest B1 B2 G3 
time ./MusicMindTest C1 B2 G3 
time ./MusicMindTest D1 B2 G3 
time ./MusicMindTest E1 B2 G3 
time ./MusicMindTest F1 B2 G3 
time ./MusicMindTest G1 B2 G3 
time ./MusicMindTest A2 B2 G3 
time ./MusicMindTest A1 C2 G3 
time ./MusicMindTest B1 C2 G3 
time ./MusicMindTest C1 C2 G3 
time ./MusicMindTest D1 C2 G3 
time ./MusicMindTest E1 C2 G3 
time ./MusicMindTest F1 C2 G3 
time ./MusicMindTest G1 C2 G3 
time ./MusicMindTest A2 C2 G3 
time ./MusicMindTest B2 C2 G3 
time ./MusicMindTest A1 D2 G3 
time ./MusicMindTest B1 D2 G3 
time ./MusicMindTest C1 D2 G3 
time ./MusicMindTest D1 D2 G3 
time ./MusicMindTest E1 D2 G3 
time ./MusicMindTest F1 D2 G3 
time ./MusicMindTest G1 D2 G3 
time ./MusicMindTest A2 D2 G3 
time ./MusicMindTest B2 D2 G3 
time ./MusicMindTest C2 D2 G3 
time ./MusicMindTest A1 E2 G3 
time ./MusicMindTest B1 E2 G3 
time ./MusicMindTest C1 E2 G3 
time ./MusicMindTest D1 E2 G3 
time ./MusicMindTest E1 E2 G3 
time ./MusicMindTest F1 E2 G3 
time ./MusicMindTest G1 E2 G3 
time ./MusicMindTest A2 E2 G3 
time ./MusicMindTest B2 E2 G3 
time ./MusicMindTest C2 E2 G3 
time ./MusicMindTest D2 E2 G3 
time ./MusicMindTest A1 F2 G3 
time ./MusicMindTest B1 F2 G3 
time ./MusicMindTest C1 F2 G3 
time ./MusicMindTest D1 F2 G3 
time ./MusicMindTest E1 F2 G3 
time ./MusicMindTest F1 F2 G3 
time ./MusicMindTest G1 F2 G3 
time ./MusicMindTest A2 F2 G3 
time ./MusicMindTest B2 F2 G3 
time ./MusicMindTest C2 F2 G3 
time ./MusicMindTest D2 F2 G3 
time ./MusicMindTest E2 F2 G3 
time ./MusicMindTest A1 G2 G3 
time ./MusicMindTest B1 G2 G3 
time ./MusicMindTest C1 G2 G3 
time ./MusicMindTest D1 G2 G3 
time ./MusicMindTest E1 G2 G3 
time ./MusicMindTest F1 G2 G3 
time ./MusicMindTest G1 G2 G3 
time ./MusicMindTest A2 G2 G3 
time ./MusicMindTest B2 G2 G3 
time ./MusicMindTest C2 G2 G3 
time ./MusicMindTest D2 G2 G3 
time ./MusicMindTest E2 G2 G3 
time ./MusicMindTest F2 G2 G3 
time ./MusicMindTest A1 A3 G3 
time ./MusicMindTest B1 A3 G3 
time ./MusicMindTest C1 A3 G3 
time ./MusicMindTest D1 A3 G3 
time ./MusicMindTest E1 A3 G3 
time ./MusicMindTest F1 A3 G3 
time ./MusicMindTest G1 A3 G3 
time ./MusicMindTest A2 A3 G3 
time ./MusicMindTest B2 A3 G3 
time ./MusicMindTest C2 A3 G3 
time ./MusicMindTest D2 A3 G3 
time ./MusicMindTest E2 A3 G3 
time ./MusicMindTest F2 A3 G3 
time ./MusicMindTest G2 A3 G3 
time ./MusicMindTest A1 B3 G3 
time ./MusicMindTest B1 B3 G3 
time ./MusicMindTest C1 B3 G3 
time ./MusicMindTest D1 B3 G3 
time ./MusicMindTest E1 B3 G3 
time ./MusicMindTest F1 B3 G3 
time ./MusicMindTest G1 B3 G3 
time ./MusicMindTest A2 B3 G3 
time ./MusicMindTest B2 B3 G3 
time ./MusicMindTest C2 B3 G3 
time ./MusicMindTest D2 B3 G3 
time ./MusicMindTest E2 B3 G3 
time ./MusicMindTest F2 B3 G3 
time ./MusicMindTest G2 B3 G3 
time ./MusicMindTest A3 B3 G3 
time ./MusicMindTest A1 C3 G3 
time ./MusicMindTest B1 C3 G3 
time ./MusicMindTest C1 C3 G3 
time ./MusicMindTest D1 C3 G3 
time ./MusicMindTest E1 C3 G3 
time ./MusicMindTest F1 C3 G3 
time ./MusicMindTest G1 C3 G3 
time ./MusicMindTest A2 C3 G3 
time ./MusicMindTest B2 C3 G3 
time ./MusicMindTest C2 C3 G3 
time ./MusicMindTest D2 C3 G3 
time ./MusicMindTest E2 C3 G3 
time ./MusicMindTest F2 C3 G3 
time ./MusicMindTest G2 C3 G3 
time ./MusicMindTest A3 C3 G3 
time ./MusicMindTest B3 C3 G3 
time ./MusicMindTest A1 D3 G3 
time ./MusicMindTest B1 D3 G3 
time ./MusicMindTest C1 D3 G3 
time ./MusicMindTest D1 D3 G3 
time ./MusicMindTest E1 D3 G3 
time ./MusicMindTest F1 D3 G3 
time ./MusicMindTest G1 D3 G3 
time ./MusicMindTest A2 D3 G3 
time ./MusicMindTest B2 D3 G3 
time ./MusicMindTest C2 D3 G3 
time ./MusicMindTest D2 D3 G3 
time ./MusicMindTest E2 D3 G3 
time ./MusicMindTest F2 D3 G3 
time ./MusicMindTest G2 D3 G3 
time ./MusicMindTest A3 D3 G3 
time ./MusicMindTest B3 D3 G3 
time ./MusicMindTest C3 D3 G3 
time ./MusicMindTest A1 E3 G3 
time ./MusicMindTest B1 E3 G3 
time ./MusicMindTest C1 E3 G3 
time ./MusicMindTest D1 E3 G3 
time ./MusicMindTest E1 E3 G3 
time ./MusicMindTest F1 E3 G3 
time ./MusicMindTest G1 E3 G3 
time ./MusicMindTest A2 E3 G3 
time ./MusicMindTest B2 E3 G3 
time ./MusicMindTest C2 E3 G3 
time ./MusicMindTest D2 E3 G3 
time ./MusicMindTest E2 E3 G3 
time ./MusicMindTest F2 E3 G3 
time ./MusicMindTest G2 E3 G3 
time ./MusicMindTest A3 E3 G3 
time ./MusicMindTest B3 E3 G3 
time ./MusicMindTest C3 E3 G3 
time ./MusicMindTest D3 E3 G3 
time ./MusicMindTest A1 F3 G3 
time ./MusicMindTest B1 F3 G3 
time ./MusicMindTest C1 F3 G3 
time ./MusicMindTest D1 F3 G3 
time ./MusicMindTest E1 F3 G3 
time ./MusicMindTest F1 F3 G3 
time ./MusicMindTest G1 F3 G3 
time ./MusicMindTest A2 F3 G3 
time ./MusicMindTest B2 F3 G3 
time ./MusicMindTest C2 F3 G3 
time ./MusicMindTest D2 F3 G3 
time ./MusicMindTest E2 F3 G3 
time ./MusicMindTest F2 F3 G3 
time ./MusicMindTest G2 F3 G3 
time ./MusicMindTest A3 F3 G3 
time ./MusicMindTest B3 F3 G3 
time ./MusicMindTest C3 F3 G3 
time ./MusicMindTest D3 F3 G3 
time ./MusicMindTest E3 F3 G3 